global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'dispatcher'
    static_configs:
      - targets: ['dispatcher:5000']

  - job_name: 'ml-worker'
    static_configs:
      - targets: ['ml_worker:9090']

  - job_name: 'camera-api'
    static_configs:
      - targets: ['camera-api:8000']
